---
title: "Research"
output:
  distill::distill_article:
    toc: TRUE
---
 
## Attitudes & Risk Perceptions of Genetic Biocontrol

I am currently a PhD student in the Conservation Sciences program at the University of Minnesota working with Dr. David Fulton to explore the public's perceptions of using genetic biocontrol to control aquatic invasive species.

Learn more about this project [here](https://maisrc.umn.edu/risk-perceptions).

<br />

## Small Game Hunters & Trappers

For my master's, working with Dr. Neelam Pouydal, I explored the motivations, constraints, expectations, and satisfaction of small game hunters and trappers in Tennessee. I analyzed responses from a mix-method survey of Tennessee small game hunters and trappers to understand the motivations of small game hunters and trappers and how various factors, such as pre-season expectations, influence individual’s satisfaction with the hunting/trapping season. Of 3,994 surveys completed (response rate 27%), 1,440 were small game hunters and trappers. Results from an exploratory factor and cluster analysis found that Tennessee small game hunters and trappers possess a variety of motivations to participate beyond harvesting an animal. Most hunters and trappers had expected the 2019-20 season to be like an average year (68%) and were satisfied with the season (65%). Results from an ordinal logistic regression revealed various factors, such as expectations and motivations to participate, influence hunters’ and trappers’ seasonal satisfaction. 


Listen to me talk about this research on the [Step Outside podcast](https://utianews.tennessee.edu/step-outside-investigating-motivations-satisfaction-and-constraints-of-small-game-hunters/)!

<br />

## Female College Students & Hunting

I am currently helping with a project lead by Dr. Lincoln Larson from the NC State University, with collaboration from universities and wildlife agencies from more than 20 different states, to investigate what factors are contributing to the decline in hunting participation and to identify ways to increase recruitment of new hunters from non-traditional hunting backgrounds, focusing on college students. In particular, I am focusing on female college students to explore (a) who are female hunters and what are their motivations to participate; (b) who are potential and lapsed female hunters, what are the constraints preventing them from participating; (c)who are female non-hunters and why are they not interested in participating in hunting?

See [Dr. Lincoln Larson's website](https://faculty.cnr.ncsu.edu/lincolnlarson/research-themes/conservation/) for more on the project. 

<br />  

## Attitudes Towards White-Nose Syndrome in Little Brown Bats

In my undergrad, with the guidance of Dr. Carly Sponarski, I examined whether different methods of communication (video vs. text) impact undergraduate student's knowledge, attitudes, and beliefs towards white-nose syndrome (WNS) in little brown bats (*Myotis lucifugus*). WNS is a deadly fungal disease that has killed millions of hibernating bats since its introduction to North America in 2006. The little brown bat, once widespread across the US, has been the most severely impacted with some colonies experiencing a 99% decline. Scientists believe changing people’s behavior is the key to bat conservation as the fungus is spread primarily by humans transferring the fungus between bat colonies. Outreach is a common method used to affect behavioral change in people, but not all outreach methods are equally effective. The purpose of this study was to investigate if different methods of media communication, video and written-text, impacted undergraduate student’s attitudes toward, beliefs toward, conservation behaviors concerning, and their knowledge toward little brown bats and WNS. Data were collected using an online survey distributed to undergraduate students at the University of Maine (n = 233). Participants were asked a set of questions before the treatment (pre-test), given either text or video outreach material, and then asked the same questions (post-test). Overall, there were no significant differences between the text and video as outreach methods in their effects on the four cognitions. There were significant changes in the four cognitions within the each treatment. Both text and video treatments positively and significantly impacted attitudes toward, beliefs toward, conservation behaviors concerning, and their knowledge toward little brown bats and WNS. These significant changes between the pre- and post-test within treatments, illustrate the impact outreach has on cognitions that support conservation.

To read more about this project, you can find my Honors thesis [here](https://digitalcommons.library.umaine.edu/honors/482/).






